import {
    app,
    BrowserWindow,
    globalShortcut,
    screen,
    ipcMain,
    Tray,
    Menu,
    nativeImage,
    dialog,
} from "electron";
import { configService } from "./services/config";
import { AppConfig } from "./shared/config";
import * as path from "path";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

// Keep global reference to the main window and tray
let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;

// Global variable to store the registered shortcut
let registeredShortcut: string | null = null;

const createTrayMenu = (accelerator: string) => {
    return Menu.buildFromTemplate([
        {
            label: "Show/Hide",
            click: () => {
                if (!mainWindow) return;
                if (mainWindow.isVisible()) {
                    mainWindow.hide();
                } else {
                    mainWindow.show();
                    mainWindow.focus();
                }
            },
            accelerator,
        },
        { type: "separator" },
        {
            label: "Settings",
            click: () => {
                if (!mainWindow) return;
                mainWindow.show();
                mainWindow.focus();
                mainWindow.webContents.send("navigate-to-settings");
            },
        },
        { type: "separator" },
        {
            label: "Quit",
            click: () => {
                app.quit();
            },
        },
    ]);
};

const updateTrayMenu = () => {
    if (!tray) return;
    const shortcutKey = configService.getGlobalShortcut();
    const contextMenu = createTrayMenu(shortcutKey);
    tray.setContextMenu(contextMenu);
};

const createTray = (): void => {
    // Create empty/default icon (you should replace this with your own icon)
    const icon = nativeImage
        .createFromPath(path.join(__dirname, "./assets/icon.png"))
        .resize({ width: 20, height: 20 }); // Resize for system tray

    tray = new Tray(icon);
    tray.setToolTip("CtrlQ");

    // Initial menu creation with current shortcut
    const shortcutKey = configService.getGlobalShortcut();
    const contextMenu = createTrayMenu(shortcutKey);
    tray.setContextMenu(contextMenu);

    // Optional: Double click on tray icon to show/hide window
    tray.on("double-click", () => {
        if (!mainWindow) return;
        if (mainWindow.isVisible()) {
            mainWindow.hide();
        } else {
            mainWindow.show();
            mainWindow.focus();
        }
    });
};

const createWindow = (): void => {
    // Get primary display dimensions
    const primaryDisplay = screen.getPrimaryDisplay();
    const { width } = primaryDisplay.workAreaSize;

    // Calculate position (right upper corner)
    const windowWidth = 400;
    const windowHeight = 400;
    const xPosition = width - windowWidth - 20; // 20px margin from right edge
    const yPosition = 20; // 40px from top

    // Create the browser window.
    mainWindow = new BrowserWindow({
        icon: path.join(__dirname, "./assets/icon.png"),
        height: windowHeight,
        width: windowWidth,
        x: xPosition,
        y: yPosition,
        frame: false, // No window frame/chrome
        transparent: true, // Allows transparent background
        resizable: false,
        show: false, // Initially hidden
        alwaysOnTop: true, // Ensures window appears on top
        skipTaskbar: true, // Doesn't show in taskbar
        center: false, // Don't center since we're setting position manually
        fullscreenable: true,
        focusable: true, // Required to accept input
        hasShadow: false,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: false,
            contextIsolation: true,
        },
    });

    mainWindow.setAlwaysOnTop(true, "screen-saver", 1);
    mainWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Register the global shortcut from config
    registerGlobalShortcut();
};

/**
 * Register global shortcut from configuration
 */
function registerGlobalShortcut() {
    // Unregister previous shortcut if exists
    if (registeredShortcut) {
        globalShortcut.unregister(registeredShortcut);
        registeredShortcut = null;
    }

    // Get shortcut from config
    const shortcutKey = configService.getGlobalShortcut();

    // Register the new shortcut
    try {
        const success = globalShortcut.register(shortcutKey, () => {
            if (!mainWindow) return;

            if (mainWindow.isVisible()) {
                mainWindow.hide();
            } else {
                // Show and focus to allow typing
                mainWindow.show();
                mainWindow.focus();

                // Ensure it remains on top after showing
                mainWindow.setAlwaysOnTop(true, "screen-saver", 1);
            }
        });

        if (success) {
            registeredShortcut = shortcutKey;
        } else {
            console.error(`Failed to register global shortcut: ${shortcutKey}`);
        }
    } catch (error) {
        console.error("Error registering shortcut:", error);
    }
}

// IPC handler to update configuration
ipcMain.handle("get-config", () => {
    return configService.getConfig();
});

// IPC handler to update configuration
ipcMain.handle("update-config", (_, newConfig: Partial<AppConfig>) => {
    const updatedConfig = configService.updateConfig(newConfig);

    // Re-register the global shortcut if hotkey changed
    if (newConfig.hotkey) {
        registerGlobalShortcut();
        // Update tray menu with new shortcut
        updateTrayMenu();
    }

    return updatedConfig;
});

// IPC handler to select folder
ipcMain.handle("select-folder", async () => {
    if (!mainWindow) return;

    const result = await dialog.showOpenDialog(mainWindow, {
        properties: ["openDirectory"],
    });

    if (!result.canceled && result.filePaths.length > 0) {
        return result.filePaths[0];
    }

    return undefined;
});

// This method will be called when Electron has finished initialization
app.whenReady().then(() => {
    createWindow();
    createTray();
});

// Quit when all windows are closed, except on macOS.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// Make sure to unregister shortcuts when quitting
app.on("will-quit", () => {
    try {
        globalShortcut.unregisterAll();
        if (tray) {
            tray.destroy();
        }
    } catch (error) {
        // Silently fail if there's an error during cleanup
    }
});
